version: 2.1

orbs:
  node: circleci/node@4.7
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:17.6.0
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: xnpm install
  linter:
    executor: my-custom-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test1:
    executor: my-custom-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run test

workflows:
  my-custom-workflow:
    jobs:
      - build
      - test1:
          requires:
            - build
      - linter:
          requires:
            - build